#!/bin/bash

set -e

VERSION=$(cat Dockerfile | grep '^ENV VERSION' | cut -d" " -f3)
TAGS=($VERSION, 6)

for TAG in "${TAGS[@]}"; do
  docker tag $IMAGE_NAME $DOCKER_REPO:$TAG
  docker push $DOCKER_REPO:$TAG
done
