# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3

      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            blacktop/elasticsearch
            ghcr.io/${{ github.repository }}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (v1)
        id: docker_build_1
        uses: docker/build-push-action@v2
        timeout-minutes: 20
        with:
          context: ./1.7
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            blacktop/elasticsearch:1
            blacktop/elasticsearch:1.7
            blacktop/elasticsearch:1.7.6
            ghcr.io/blacktop/elasticsearch:1
            ghcr.io/blacktop/elasticsearch:1.7
            ghcr.io/blacktop/elasticsearch:1.7.6
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image (v6)
        id: docker_build_6
        uses: docker/build-push-action@v2
        timeout-minutes: 20
        with:
          context: ./6.8
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            blacktop/elasticsearch:6
            blacktop/elasticsearch:6.8
            blacktop/elasticsearch:6.8.23
            ghcr.io/blacktop/elasticsearch:6
            ghcr.io/blacktop/elasticsearch:6.8
            ghcr.io/blacktop/elasticsearch:6.8.23
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image (v7)
        id: docker_build_7
        uses: docker/build-push-action@v2
        timeout-minutes: 20
        with:
          context: ./7.17
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            blacktop/elasticsearch:7
            blacktop/elasticsearch:7.17
            blacktop/elasticsearch:7.17.2
            ghcr.io/blacktop/elasticsearch:7
            ghcr.io/blacktop/elasticsearch:7.17
            ghcr.io/blacktop/elasticsearch:7.17.2
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image (v8)
        id: docker_build_8
        uses: docker/build-push-action@v2
        timeout-minutes: 20
        with:
          context: ./8.1
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            blacktop/elasticsearch:latest
            blacktop/elasticsearch:8
            blacktop/elasticsearch:8.1
            blacktop/elasticsearch:8.1.2
            ghcr.io/blacktop/elasticsearch:latest
            ghcr.io/blacktop/elasticsearch:8
            ghcr.io/blacktop/elasticsearch:8.1
            ghcr.io/blacktop/elasticsearch:8.1.2
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}

      # - name: Build and push Docker image (X-Pack)
      #   id: docker_build_x_pack
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./x-pack
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: |
      #       blacktop/elasticsearch:x-pack
      #       blacktop/elasticsearch:x-pack-7
      #       blacktop/elasticsearch:x-pack-7.15
      #       blacktop/elasticsearch:x-pack-7.15.1
      #     labels: ${{ steps.meta.outputs.labels }}
