# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker Image

on:
  push:
    branches:
      - 'master'

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [
          {
            name: "v1",
            versions: "1 1.7 1.7.6"
          },
          {
            name: "v2",
            versions: "1 1.7 1.7.6"
          },
          {
            name: "v6",
            versions: "1 1.7 1.7.6"
          },
          {
            name: "v7",
            versions: "1 1.7 1.7.6"
          },
          {
            name: "v8",
            versions: "1 1.7 1.7.6"
          }
        ]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Create images list for $ {{ matrix.versions.name }}
        env:
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          VERSION_LIST: ${{ matrix.versions.versions }}
        run: |
          IMAGE_LIST=""

          if [ "$REPOSITORY_OWNER" = "blacktop" ] ; then
            for version in $VERSION_LIST; do
              IMAGE_LIST="$IMAGE_LIST\nblacktop/elasticsearch:$version"
            done
          fi

          for version in $VERSION_LIST; do
            IMAGE_LIST="$IMAGE_LIST\ghcr.io/$REPOSITORY_OWNER/elasticsearch:$version"
          done

          echo $IMAGE_LIST
